name: webolutionary
recipe: pantheon
config:
  framework: drupal8
  site: webolutionary
  id: da848ed7-9c52-4e9c-a2dd-6f255d766d85
  drupal: true
services:
  appserver:
    build:
      - "cp -rf /app/terminus.config.yml $HOME/.terminus/config.yml"
      - "terminus auth:login"
      - "rm -rf $HOME/.terminus/plugins"
      - "mkdir -p $HOME/.terminus/plugins"
      - "composer create-project -d $HOME/.terminus/plugins pantheon-systems/terminus-build-tools-plugin:~1"
      - "composer create-project --no-dev -d $HOME/.terminus/plugins pantheon-systems/terminus-drupal-console-plugin:~1"
      - "terminus self:clear-cache"
      - "cd /app && composer install"
tooling:
  drush:
    service: appserver
    cmd:
      - "drush"
      - "--root=/app/web"
      - "--uri=https://webolutionary.lndo.site"
