name: webolutionary
recipe: pantheon
config:
  framework: drupal8
  site: webolutionary
  id: da848ed7-9c52-4e9c-a2dd-6f255d766d85
  drupal: true
  webroot: web
  php: '7.4'
  composer_version: '1.10.22'
services:
  appserver:
    build:
      - "rm -rf ~/.terminus/plugins"
      - "mkdir -p ~/.terminus/plugins"
      - "cp -rf /app/terminus.config.yml ~/.terminus/config.yml"
      - "terminus auth:login"
      - "composer create-project -d ~/.terminus/plugins pantheon-systems/terminus-build-tools-plugin:~2"
      - "composer create-project --no-dev -d ~/.terminus/plugins pantheon-systems/terminus-drupal-console-plugin:~1"
      - "terminus self:clear-cache"
      - "cd /app && composer install"
  patterns:
    type: php:7.4
    via: cli
    build_as_root:
      - "apt-get update && apt-get -y install \
         libatk-bridge2.0-0 \
         libasound2 \
         libgtk-3.0 \
         libnss3 \
         libx11-6 \
         libx11-xcb1 \
         libxss1 \
         libxtst6"
      - "curl -sL https://deb.nodesource.com/setup_8.x | bash - && apt-get install -y nodejs"
      - "nodejs -v"
      - "cd /app/web/themes/custom/webolutionary && npm install"
    overrides:
      ports:
        - 3000:3000
proxies:
  patterns:
    - patterns.webolutionary.lndo.site:3000
tooling:
  drush:
    service: appserver
    cmd: "drush --root=/app/web --uri=https://webolutionary.lndo.site"
  watch:
    service: patterns
    cmd: "npm start --prefix=/app/web/themes/custom/webolutionary"
