name: webolutionary
recipe: pantheon
config:
  framework: drupal8
  site: webolutionary
  id: da848ed7-9c52-4e9c-a2dd-6f255d766d85
  drupal: true
services:
  appserver:
    build:
      - "cp -rf /app/terminus.config.yml $HOME/.terminus/config.yml"
      - "terminus auth:login"
      - "rm -rf $HOME/.terminus/plugins"
      - "mkdir -p $HOME/.terminus/plugins"
      - "composer create-project -d $HOME/.terminus/plugins pantheon-systems/terminus-build-tools-plugin:~1"
      - "composer create-project --no-dev -d $HOME/.terminus/plugins pantheon-systems/terminus-drupal-console-plugin:~1"
      - "terminus self:clear-cache"
      - "cd /app && composer install"
  node:
    type: 'node:8.4'
    globals:
      gulp-cli: "latest"
    extras:
      - "apt-get update -y"
      - "apt-get install -y \
         curl \
         php5-cli \
         git \
         unzip \
         gconf-service \
         libasound2 \
         libatk1.0-0 \
         libcups2 \
         libdbus-1-3 \
         libgconf-2-4 \
         libgtk-3-0 \
         libnspr4 \
         libx11-xcb1 \
         libxcomposite1 \
         libxcursor1 \
         libxdamage1 \
         libxfixes3 \
         libxi6 \
         libxrandr2 \
         libxss1 \
         libxtst6 \
         libappindicator1 \
         libnss3 \
         lsb-release"
      - "curl -sS https://getcomposer.org/installer -o composer-setup.php"
      - "php composer-setup.php --install-dir=/usr/local/bin --filename=composer"
      - "rm -f composer-setup.php"
    build:
      - "rm -rf /app/web/themes/custom/webolutionary/pattern-lab /app/web/themes/custom/webolutionary/node_modules"
      - "cd /app/web/themes/custom/webolutionary && npm install -y"
      - "cd /app/web/themes/custom/webolutionary && npm run install-pattern-lab"
      - "cd /app/web/themes/custom/webolutionary && npm run sass"
    overrides:
      services:
        ports:
          - 8088:8088
proxy:
  node:
    - patterns.webolutionary.lndo.site:8088
tooling:
  node:
    service: node
  npm:
    service: node
  run:
    service: node
    user: root
    cmd:
      - "npm"
      - "run"
      - "--prefix=/app/web/themes/custom/webolutionary"
  drush:
    service: appserver
    cmd:
      - "drush"
      - "--root=/app/web"
      - "--uri=https://webolutionary.lndo.site"
