use_format_specific_options: true
default_highlighting: GESHIFILTER_DEFAULT_DONOTHING
default_line_numbering: 1
use_highlight_string_for_php: false
enable_keyword_urls: true
decode_entities: true
css_mode: 1
code_container: '3'
tags: 'code blockcode'
tag_styles:
  1: 1
  2: 2
  4: 0
  8: 0
  16: 0
tab_width: 8
language:
  php:
    enabled: true
    tags: php
  cpp:
    tags: cpp
  java: {  }
  bash:
    enabled: true
    tags: bash
  css:
    enabled: true
    tags: css
  html5:
    enabled: true
    tags: html
  javascript:
    enabled: true
    tags: javascript
  jquery:
    enabled: true
    tags: jquery
  mysql:
    enabled: true
    tags: mysql
  sass:
    enabled: true
    tags: sass
  twig:
    enabled: true
    tags: twig
  yaml:
    enabled: true
    tags: yaml
_core:
  default_config_hash: 1jZtSc2CSiEBA45nbX0wMKFY3bmcilIwOBQCKFscK0U
